# Name of your server
server-name: "HCF CORE"
# Description of your server
server-description: "TEXT FROM HCF"
# Map from server from HCF (Hardcore Factions)
server-map: "1"

# Spawn
border-limit: 
 overworld: 2000
 nether: 1000
 end: 500

# Discord
webhook-url: ""
webhook-check: false
 
faction:
  name:
    maximum: 20
    banned:
      - "GreekMCOnTop"
      - "InfinityOnTop"
      - "Player"
      - "Owner"
      - "OnTop"
 claim:
    maximum: 80
    price-per-block: 15
 deaths-until-raidable:
    maximum: 4.5
    regeneration: 1.5
    frezee-time: 360
    lose: 0.5
 max-players: 5
 logs: false
 start-balance: 1000

# How much is the maximum effect you want on items?
# NOTE: in general not just one item
max-effect-amplifier: 1

# I recommend having a global database, to have compatibility or when transferring to another host and not lose data
mysql:
 #Database Host IP
 host: "127.0.0.1"
 #Database name, the classic "s344_HCF"
 dbname: "HCF"
 #database port
 port: 3306
 #Database user
 username: "srclau"
 #Database password
 password: "contraseña"
